### ISSUE TITLE
Stick icon is broken in PC version

### ISSUE THREAD

**Issue by iammeken** [flaubert-dev/really-simple-theme#1]
Thank you for this free but super fast and lovely theme!

There is one issue:  Stick icon (Paperclip) of post on the front page is broken in PC version.  It is ok in mobile version.

Can you fix it when you have time?

**Comment by flaubert-dev** [comment]
Hello @iammeken, thank you very much for your feedback.

Sorry for the delay in responding to you. This year 2024 I am very busy. 

As soon as I find some free time I will definitely resolve this issue.

I'll leave this issue open, as soon as it's resolved I'll let you know.

**Comment by flaubert-dev** [comment]
> Thank you for this free but super fast and lovely theme!
> 
> There is one issue: Stick icon (Paperclip) of post on the front page is broken in PC version. It is ok in mobile version.
> 
> Can you fix it when you have time?

I already made the correction for a new icon, now it will work ✅ 

I tested it on edge, chrome, firefox and opera browsers and now it is working fine ✅ 

Please, if you have any problems, just let me know or open a new >> [issues](https://github.com/flaubert-dev/really-simple-theme/issues) << 👍 

Notable improvements will come sometime in the future in the major update to version 2.0.0 📈

**Comment by iammeken** [comment]
Thank you for your time!  Good luck!
